#! /bin/sh

# Autostart
xrdb -merge ~/.Xresources
xset r rate 300 50 &
xsetroot -cursor_name left_ptr
~/.fehbg &
picom &
dunst &

# Polybar autostart
~/.config/polybar/launch.sh --colorblocks

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config border_width         6
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Coloring
bspc config focused_border_color	 "#9e9e9e"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
